version: '3.8'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    ports:
      - "8081:8081"
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - telegram_bot_api_data:/var/lib/telegram-bot-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/bot${TELEGRAM_BOT_TOKEN}/getMe"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  telegram_bot_api_data:
